# Generated by Django 4.1.7 on 2023-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('area', models.CharField(max_length=40, verbose_name='Area')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
            ],
        ),
    ]
